title: Setup Canon Ij Printer Step By Step 
description: Setting up canon ij printer is pretty easy just follow the Following points that come under the Ij canon setup activation process.
theme: jekyll-theme-tactile
